chore(workflows): Add additional debugging to publish

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -89,7 +89,12 @@ jobs:
 
       - name: Publish to NPM
         if: steps.decision.outputs.should_release == 'true'
-        run: pnpm publish --access public --filter @tsfx/${{ matrix.package }} --loglevel verbose
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+        run: |
+          cat ~/.npmrc || echo "INFO: ~/.npmrc not found or unreadable."
+          pnpm whoami --registry https://registry.npmjs.org/
+          pnpm publish --access public --filter @tsfx/${{ matrix.package }}
 
       - name: Structure dist for release
         if: steps.decision.outputs.should_release == 'true'
